# Site wide configuration

title:            Benjamin Braun
locale:           en_US
url:              http://www.benbraun.net
#url:              http://localhost:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Benjamin Braun
  avatar: bio-photo.jpg
  bio: "Computer Science Graduate Student at UCSD"
  email: mailhide
  disqus-shortname: benbraun
  twitter: #username
  facebook: benbraunster
  google:
    plus: BenjaminBraun2
    analytics: UA-55663110-1
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: benbraun
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: benbraun1
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
